spring:
  application:
    name: spring-profiles-demo

    #You can change this value to any environment i.e. dev, test and prod
  profiles:
    active: dev

    #dev have most priority (prod has less priority). priority goes from left to right.
    #active: prod, test, dev

server:
  port: 8080

  #java -jar your-app.jar --spring.profiles.active=prod
  #mvn spring-boot:run -Dspring-boot.run.profiles=dev